### ISSUE TITLE
Synchronization on database query

### ISSUE THREAD

**Issue by dorfri** [maxmind/MaxMind-DB-Reader-java#11]
Hi

When invoking Reader's get method, I noticed that I reach a synchronized method in BufferHolder.get() - which has a performance impact when we are using several threads. 
I do not understand why this synchronization is needed... you are just duplicating a read-only value...

In general, since everything is in memory (I am working in MEMORY file mode) - it seems weird that you have to synchronize between threads. 
Is there is a way to use the API without having this synchronization?

Thanks!
Doron.

**Comment by oschwald** [comment]
Closing as profiling hasn't shown this to be an issue. I am happy to re-open if new information comes to light.
