### ISSUE TITLE
Feature Inquiry: Native extension similar to Python?

### ISSUE THREAD

**Issue by beamerblvd** [maxmind/MaxMind-DB-Reader-java#15]
The Python version of this library has a native extension (compiled against libmaxminddb) that improves performance of the library. Is there a plan to implement such a native extension for this Java library?

Would such an extension even provide a performance boost in Java, or is the Java memory mapping already as fast as it can get?

If such an extension would provide a benefit, I'd like to propose it as a feature for an upcoming release.

**Comment by oschwald** [comment]
The Java API outperforms the Python API with the C extension. It is unlikely that it would be noticeably faster using the C library via JNI. There are probably optimizations to be done to reduce the number of allocations it makes, although I think all of the easy ones have been addressed.

**Comment by beamerblvd** [comment]
Cool. Thanks!

**Comment by oschwald** [comment]
I am going to close for the reasons mentioned above.
