### ISSUE TITLE
Dont use ranges for jackson dependency

### ISSUE THREAD

**Issue by devshorts** [maxmind/MaxMind-DB-Reader-java#28]
https://github.com/maxmind/MaxMind-DB-Reader-java/blob/v1.2.1/pom.xml#L40

Using a range for the jackson dependency causes snapshots to be pulled in. Maven's range capabilities seems kinda busted, since using a deployed pinned version of MaxMind reader pulls in jackson 2.9.0-SNAPSHOT as of today.  

This really messes with your determinism of your artifacts and depending on snapshots is in general bad juju for non-beta libraries. 

From the following [SO](http://stackoverflow.com/questions/4407055/how-do-i-stop-maven-version-ranges-from-using-snapshots) and [disucssion](http://maven.40175.n5.nabble.com/maven-3-version-ranges-with-snapshots-td4393464.html)
 the consensus seems to be don't use ranges

**Comment by oschwald** [comment]
This has already been fixed in 1.2.2.

**Comment by devshorts** [comment]
@oschwald thanks! Didn't know that, appreciate it :)
