### ISSUE TITLE
Update jackson-databind to 2.9.2 to align with MaxMind GeoIP2 API 2.10.0

### ISSUE THREAD

**Issue by karraar** [maxmind/MaxMind-DB-Reader-java#33]
MaxMind GeoIP2 API is now using jackson-databind 2.9.2 and to minimize conflict MaxMind-DB-Reader-java should update to the same version.

**Comment by oschwald** [comment]
Did this cause a particular issue for you?

**Comment by karraar** [comment]
Implementing the geoip2 Java API in a Apache Spark job is causing conflict with jackson-databind compatibility issues.  I'm not 100% sure if having the current version is the only conflict or if it is a conflict at all, but dependency:tree showed those 2 versions were being pulled and a compatibility error message generated.
