### ISSUE TITLE
Jackson dependency?

### ISSUE THREAD

**Issue by tinspin** [maxmind/MaxMind-DB-Reader-java#48]
I tried long and hard to understand why you opted to force developers to use 2MB dependency to retrieve data that has no problem being stored in a String.

But I failed.

So I downloaded this instead: https://www.miyuru.lk/geoiplegacy

**Comment by oschwald** [comment]
The data is not a simple string. Depending on the database, it can be a fairly complicated data structure. See [the format specification](https://github.com/maxmind/MaxMind-DB/blob/master/MaxMind-DB-spec.md#output-data-section) for more information. `jackson-databind` is used for deserialization of this structure to model objects.
