### ISSUE TITLE
Non blocking APIs for Database Reader

### ISSUE THREAD

**Issue by tiwarivikash** [maxmind/MaxMind-DB-Reader-java#64]
Any plans to expose non-blocking APIs?

**Comment by oschwald** [comment]
The library generally does not use the file IO APIs to read the file. The only place where we do is when you pass the constructor and use `FileMode.MEMORY`. If you want to use memory mode and read in the file using a non-blocking method, you could achieve this by reading in the file yourself and using the constructor that takes a stream.

Given this, I don't think adding a non-blocking API makes sense.
