### ISSUE TITLE
Unsafe memory access operation

### ISSUE THREAD

**Issue by simPod** [maxmind/MaxMind-DB-Reader-java#81]
We're using GeoIP (licensed db).

Following code is run in multiple threads (the static `cityDatabaseReader` property is shared).  
The `reloadDatabase()` method is called periodically. First time in the constructor to initiate the db and then there's scheduled call in parent class to refresh database.

When the code is initially run it works as expected but on second `reloadDatabase()` call (from scheduler in parent class) it crashes with following error:

> java.lang.InternalError: a fault occurred in a recent unsafe memory access operation in compiled Java code

```java
public class GeoAppender extends ContextRefresher {
    @SuppressWarnings("NullAway.Init")
    private static volatile DatabaseReader cityDatabaseReader;

    public GeoAppender() {
        super(Duration.ofHours(4));

        reloadDatabase();
    }

    @Override
    public void process(InetAddress ip) {
        try {
            CityResponse cityResponse = cityDatabaseReader.city(ip);
            ...
        } catch (GeoIp2Exception | IOException ignored) {
        }

        ...
    }

    private void reloadDatabase() {
        File file = new File("path/to/city.mmdb);

        try {
            cityDatabaseReader = new DatabaseReader
                .Builder(file)
                .withCache(new CHMCache())
                .build();
        } catch (IOException exception) {
            throw new RuntimeException(exception.getMessage());
        }
    }

}
```

```
Exception in thread "my.app.StreamThread-24" java.lang.InternalError: a fault occurred in a recent unsafe memory access operation in compiled Java code
	at java.base/java.nio.Buffer.checkIndex(Buffer.java:681)
	at java.base/java.nio.DirectByteBuffer.get(DirectByteBuffer.java:269)
	at com.maxmind.db.Reader.readNode(Reader.java:223)
	at com.maxmind.db.Reader.getRecord(Reader.java:170)
	at com.maxmind.geoip2.DatabaseReader.get(DatabaseReader.java:273)
	at com.maxmind.geoip2.DatabaseReader.getOrThrowException(DatabaseReader.java:240)
	at com.maxmind.geoip2.DatabaseReader.city(DatabaseReader.java:330)
	at my_ns..GeoAppender.process(GeoAppender.java:52)
	at my_ns..GeoAppender.process(GeoAppender.java:16)
```

**Comment by oschwald** [comment]
What OS and what JDK version are you using? How are you updating the underlying mmdb file?

My first thought is that the file is that perhaps the file is not being replaced atomically.

**Comment by simPod** [comment]
Even though the file is not updated (the same file for init and reload) the error occurs. So basically running this outside of constructor

```java
    private void reloadDatabase() {
        File file = new File("path/to/city.mmdb);

        try {
            cityDatabaseReader = new DatabaseReader
                .Builder(file)
                .withCache(new CHMCache())
                .build();
        } catch (IOException exception) {
            throw new RuntimeException(exception.getMessage());
        }
    }
```

causes it. 

Debian 4.19.132-1 (2020-07-24) x86_64
Java 11

**Comment by oschwald** [comment]
I tried reproducing this and could not. Would you be able to make a self-contained test case?

**Comment by simPod** [comment]
I understand. Thank you for trying. I'll make an attempt to isolate it, will take a while though, it's complex. Will be in touch.

**Comment by oschwald** [comment]
Any updates on this?

**Comment by simPod** [comment]
I believe the issue is invalid. Did not realise the app touches the file and the db is not fully in memory. Then when the db file gets replaced there might be some ops running over the old file. Thank you!

**Comment by oschwald** [comment]
Thanks for the update. On POSIX systems, if you replace the file atomically, this shouldn't be an issue. For instance, move the file to the same file system as the old one but with a new name and then move it over the old file. This leaves the old file in place and unmodified for anything that has it open already but a new instance will see the new file.

**Comment by simPod** [comment]
Yes, I was overwriting the file. Will try to move it instead.
