### ISSUE TITLE
InvalidDatabaseException The MaxMind DB file's search tree is corrupt: contains pointer larger than the database.

### ISSUE THREAD

**Issue by Aashima89** [maxmind/MaxMind-DB-Reader-java#87]

**Comment by Aashima89** [comment]
Hi, I am using maxmind reader to resolve ips but getting error on one of my EC2 containers. Though rest of them are able to read from the file successfully. Had a question on when do we see such error? I did go through the code but couldn't understand the reasoning of when such case can happen!

**Comment by oschwald** [comment]
As the exception message suggests, it sounds like the file is corrupt.

**Comment by Aashima89** [comment]
The other containers running parallely were able to access the file from the same  `mappingFilePath`

**Comment by oschwald** [comment]
I am not really in a position to debug why the one container was different. That exception is thrown on an invalid database. Perhaps there is corruption that only affects a particular record or perhaps the file was being updated/written when the container opened it.

**Comment by oschwald** [comment]
Closing as there is not enough information in this issue to further debug it. Feel free to reopen with more details.

**Comment by Aashima89** [comment]
Thanks @oschwald for addressing. Found out that the file was replaced from below and the reader was initialized with old file reference so on replacement it started throwing the above error
