### ISSUE TITLE
Where can I download the .mmdb file?

### ISSUE THREAD

**Issue by sa2241182** [maxmind/MaxMind-DB-Reader-java#99]
Where can I download the .mmdb file?

**Comment by oschwald** [comment]
You can [sign up for GeoLite2](https://dev.maxmind.com/geoip/geolite2-free-geolocation-data?lang=en) or you can [purchase a GeoIP2 database](https://www.maxmind.com/en/geoip2-services-and-databases). There are also several third party databases.
